#!/bin/bash
##########################################################################################
#																						 #
#						toxsign_enrich - qsub_preEnrich									 #
#				Qsub all tcl scripts using activeTCL 8.6                       			 #
#				DO NOT edit this file													 #
#				edit config.ini instead													 #
##########################################################################################
echo 'toxsign_enrich - qsub_h2mpo'

. /local/env/envactivetcvl-8.6.sh


wish8.6 $1"homologene2mpo.tcl" -hg $2 -gene2mgi $3 -mgi2mpo $4 -mpoobo $5 -o $6