#!/bin/bash

##########################################################################################
#																						 #
#						toxsign_enrich - qsub_wish										 #
#				Qsub all tcl scripts using activeTCL 8.6                       			 #
#				DO NOT edit this file													 #
#				edit config.ini instead													 #
##########################################################################################
echo 'toxsign_enrich - qsub_h2hpo'

. /local/env/envactivetcvl-8.6.sh
wish8.6 $1"homologene2hpo.tcl" -hg $2 -gene2hpo $3 -hpoobo $4 -o $5