#!/bin/bash
##########################################################################################
#																						 #
#						toxsign_enrich - qsub_preEnrich									 #
#				Qsub all tcl scripts using activeTCL 8.6                       			 #
#				DO NOT edit this file													 #
#				edit config.ini instead													 #
##########################################################################################
echo 'toxsign_enrich - qsub_preEnrich'

. /local/env/envactivetcvl-8.6.sh
. /local/env/envR-3.2.3.sh

echo $1
echo $2
echo $3
echo $4
echo $5

wish8.6 $4"prepare_enrichment.tcl" -hg2go $1 -sign $2 -o $3
Rscript $4"compute_enrichment.R" $3 $5